export const ACTIVATE_ADD_MODE = 'ACTIVATE_ADD_MODE'
export const ACTIVATE_VIZ_MODE = 'ACTIVATE_VIZ_MODE'
export const REQUEST_GYMS = 'REQUEST_GYMS'
export const UPDATE_NEW_GYM_COORD = 'UPDATE_NEW_GYM_COORD'
export const SEND_ADD_GYM = 'SEND_ADD_GYM';
export const ACTIVATE_ADD_COMMENT_MODE = 'ACTIVATE_ADD_COMMENT_MODE';
export const DISPLAY_GYM_INFO = 'DISPLAY_GYM_INFO'
export const RECEIVE_GYMS = 'RECEIVE_GYMS'
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
export const SET_LANGUAGE = 'SET_LANGUAGE'

